/* ==========================================================================
   BANK MANDIRI REGION V - MASTER DATASET MERCHANT & DEBITUR KEBAYORAN BARU
   Database Merchant & Potensi Pembiayaan KUR/KUM: Blok M, Blok C, & Blok O
   ========================================================================== */

window.MASTER_BLOKM_MERCHANTS = [
  // --- ZONA BLOK M ---
  {
    id: "BM-001",
    namaUsaha: "Bakmi GM Blok M Square",
    kategori: "F&B / Kuliner",
    zonaUtama: "Blok M",
    subZona: "Blok M Square",
    alamat: "Blok M Square Lt. GF Unit 12, Jl. Melawai V",
    lat: -6.2443,
    lng: 106.8018,
    telepon: "081298765431",
    omsetBulanan: "Rp 185.000.000",
    volumeSettlement: "Rp 142.000.000",
    statusNasabah: "TARGET_KUR",
    statusText: "Target Cross-Selling KUR",
    potensiKredit: "Rp 250.000.000 (KUR Mikro)",
    terminal: "EDC Mandiri + QRIS",
    keterangan: "Usaha kuliner rame pengunjung. Belum ada pinjaman suplesi modal."
  },
  {
    id: "BM-002",
    namaUsaha: "Toko Mas Cantik Melawai",
    kategori: "Retail & Perhiasan",
    zonaUtama: "Blok M",
    subZona: "Melawai",
    alamat: "Pertokoan Melawai Plaza Lt. 1 No. 45",
    lat: -6.2455,
    lng: 106.8005,
    telepon: "081311223344",
    omsetBulanan: "Rp 450.000.000",
    volumeSettlement: "Rp 320.000.000",
    statusNasabah: "DEBITUR_EKSISTING",
    statusText: "Debitur Mandiri Eksisting",
    potensiKredit: "KUM Rp 500.000.000 (Top Up Active)",
    terminal: "EDC Android Dual SIM",
    keterangan: "Nasabah eksisting kolektibilitas lancar. Membutuhkan tambahan limit akhir tahun."
  },
  {
    id: "BM-003",
    namaUsaha: "Fukuya Japanese Restaurant",
    kategori: "F&B / Kuliner",
    zonaUtama: "Blok M",
    subZona: "Melawai",
    alamat: "Jl. Melawai VI No. 8, Little Tokyo",
    lat: -6.2461,
    lng: 106.8012,
    telepon: "085712345678",
    omsetBulanan: "Rp 290.000.000",
    volumeSettlement: "Rp 210.000.000",
    statusNasabah: "TARGET_KUR",
    statusText: "Target Cross-Selling KUR",
    potensiKredit: "Rp 300.000.000 (KUM Komersial)",
    terminal: "QRIS Dinamis Livin Merchant",
    keterangan: "Restoran Jepang teramai di Little Tokyo. Transaksi QRIS sangat aktif."
  },
  {
    id: "BM-004",
    namaUsaha: "Batik Keris Pasar Raya",
    kategori: "Fashion & Craft",
    zonaUtama: "Blok M",
    subZona: "Pasar Raya",
    alamat: "Pasaraya Grande Lt. 2 Wing A",
    lat: -6.2428,
    lng: 106.8008,
    telepon: "081809876543",
    omsetBulanan: "Rp 160.000.000",
    volumeSettlement: "Rp 98.000.000",
    statusNasabah: "DEBITUR_EKSISTING",
    statusText: "Debitur Mandiri Eksisting",
    potensiKredit: "KUR Rp 100.000.000 (Running)",
    terminal: "EDC Mandiri POS",
    keterangan: "Outlet fashion batik etnik. Angsuran tepat waktu setiap bulan."
  },
  {
    id: "BM-005",
    namaUsaha: "Titik Temu Coffee M-Bloc",
    kategori: "F&B / Cafe",
    zonaUtama: "Blok M",
    subZona: "M-Bloc",
    alamat: "M-Bloc Space House No. 3, Jl. Panglima Polim",
    lat: -6.2412,
    lng: 106.7985,
    telepon: "081288990011",
    omsetBulanan: "Rp 210.000.000",
    volumeSettlement: "Rp 175.000.000",
    statusNasabah: "TARGET_KUR",
    statusText: "Target Cross-Selling KUR",
    potensiKredit: "Rp 200.000.000 (KUR Ekspansi Branch)",
    terminal: "QRIS Soundbox + EDC Mandiri",
    keterangan: "Cafe hits anak muda M-Bloc. Rencana buka cabang baru di Senopati."
  },
  {
    id: "BM-006",
    namaUsaha: "Apotek K-24 Plaza Blok M",
    kategori: "Kesehatan & Farmasi",
    zonaUtama: "Blok M",
    subZona: "Plaza Blok M",
    alamat: "Plaza Blok M Lt. Lower Ground No. 08",
    lat: -6.2432,
    lng: 106.7978,
    telepon: "081399887766",
    omsetBulanan: "Rp 310.000.000",
    volumeSettlement: "Rp 245.000.000",
    statusNasabah: "DEBITUR_EKSISTING",
    statusText: "Debitur Mandiri Eksisting",
    potensiKredit: "KUM Rp 400.000.000 (Active)",
    terminal: "EDC Android + QRIS Statis",
    keterangan: "Buka 24 Jam terhubung langsung dengan integrasi pintu MRT."
  },

  // --- ZONA BLOK C ---
  {
    id: "BC-001",
    namaUsaha: "Toko Tekstil Fancy Mayestik",
    kategori: "Retail & Perhiasan",
    zonaUtama: "Blok C",
    subZona: "Pasar Mayestik",
    alamat: "Pasar Mayestik Lt. Semi Basement Blok A No. 12",
    lat: -6.2392,
    lng: 106.7928,
    telepon: "081244556677",
    omsetBulanan: "Rp 380.000.000",
    volumeSettlement: "Rp 290.000.000",
    statusNasabah: "TARGET_KUR",
    statusText: "Target Cross-Selling KUR",
    potensiKredit: "Rp 350.000.000 (KUM Komersial)",
    terminal: "EDC Android + QRIS Livin",
    keterangan: "Grosir kain impor ternama di Mayestik. Kebutuhan modal kerja stok lebaran."
  },
  {
    id: "BC-002",
    namaUsaha: "Bakmi Boy Mayestik",
    kategori: "F&B / Kuliner",
    zonaUtama: "Blok C",
    subZona: "Pasar Mayestik",
    alamat: "Jl. Kyai Maja No. 33C, Kebayoran Baru",
    lat: -6.2405,
    lng: 106.7942,
    telepon: "081599881122",
    omsetBulanan: "Rp 220.000.000",
    volumeSettlement: "Rp 165.000.000",
    statusNasabah: "DEBITUR_EKSISTING",
    statusText: "Debitur Mandiri Eksisting",
    potensiKredit: "KUR Rp 200.000.000 (Active)",
    terminal: "EDC Mandiri POS",
    keterangan: "Kuliner bakmi legendaris sejak 1963. Pembayaran angsuran lancar."
  },
  {
    id: "BC-003",
    namaUsaha: "Klinik Medika Kyai Maja",
    kategori: "Kesehatan & Farmasi",
    zonaUtama: "Blok C",
    subZona: "Barito",
    alamat: "Jl. Kyai Maja No. 88, Barito",
    lat: -6.2425,
    lng: 106.7932,
    telepon: "081377889900",
    omsetBulanan: "Rp 410.000.000",
    volumeSettlement: "Rp 310.000.000",
    statusNasabah: "TARGET_KUR",
    statusText: "Target Cross-Selling KUR",
    potensiKredit: "Rp 500.000.000 (KUM Komersial Plus)",
    terminal: "EDC Mandiri Dual SIM",
    keterangan: "Klinik spesialis dan laboratorium. Rencana pengadaan alat USG baru."
  },
  {
    id: "BC-004",
    namaUsaha: "Sentra Satwa Barito",
    kategori: "Retail & Perhiasan",
    zonaUtama: "Blok C",
    subZona: "Barito",
    alamat: "Taman Barito No. 14, Jl. Barito Raya",
    lat: -6.2442,
    lng: 106.7948,
    telepon: "085699001122",
    omsetBulanan: "Rp 120.000.000",
    volumeSettlement: "Rp 85.000.000",
    statusNasabah: "TARGET_KUR",
    statusText: "Target Cross-Selling KUR",
    potensiKredit: "Rp 100.000.000 (KUR Mikro)",
    terminal: "QRIS Soundbox Livin",
    keterangan: "Kios perlengkapan hewan peliharaan & pakan. Transaksi harian sangat tinggi."
  },



  // --- ZONA BLOK N ---
  {
    id: "BN-001",
    namaUsaha: "Plataran Dharmawangsa",
    kategori: "F&B / Kuliner",
    zonaUtama: "Blok N",
    subZona: "Dharmawangsa",
    alamat: "Jl. Dharmawangsa Raya No. 6, Kebayoran Baru",
    lat: -6.2482,
    lng: 106.8015,
    telepon: "081299887766",
    omsetBulanan: "Rp 520.000.000",
    volumeSettlement: "Rp 410.000.000",
    statusNasabah: "TARGET_KUR",
    statusText: "Target Cross-Selling KUR",
    potensiKredit: "Rp 500.000.000 (KUM Komersial)",
    terminal: "EDC Mandiri Android POS",
    keterangan: "Restoran fine dining heritage Indonesia. Prospek fasilitas kredit modal kerja."
  },
  {
    id: "BN-002",
    namaUsaha: "Boutique Hotel Dharmawangsa",
    kategori: "Jasa & Perhotelan",
    zonaUtama: "Blok N",
    subZona: "Dharmawangsa",
    alamat: "Jl. Brawijaya VIII No. 12",
    lat: -6.2498,
    lng: 106.8028,
    telepon: "081377889900",
    omsetBulanan: "Rp 680.000.000",
    volumeSettlement: "Rp 540.000.000",
    statusNasabah: "DEBITUR_EKSISTING",
    statusText: "Debitur Mandiri Eksisting",
    potensiKredit: "KUM Rp 500.000.000 (Active)",
    terminal: "EDC Mandiri Dual SIM",
    keterangan: "Hotel boutique kawasan elite Dharmawangsa. Transaksi settlement QRIS & EDC sangat tinggi."
  },
  {
    id: "BN-003",
    namaUsaha: "Union Deli Brawijaya",
    kategori: "F&B / Cafe",
    zonaUtama: "Blok N",
    subZona: "Wijaya",
    alamat: "Jl. Brawijaya Raya No. 4A",
    lat: -6.2472,
    lng: 106.8042,
    telepon: "081833445566",
    omsetBulanan: "Rp 380.000.000",
    volumeSettlement: "Rp 290.000.000",
    statusNasabah: "TARGET_KUR",
    statusText: "Target Cross-Selling KUR",
    potensiKredit: "Rp 350.000.000 (KUR Mikro/Small)",
    terminal: "QRIS Soundbox + Livin Merchant",
    keterangan: "Bakery & cafe hits koridor Dharmawangsa-Brawijaya."
  }
];
